As a result of r21308, if we are building with "--disable-mpi-io " make sure that MPI_MAX_DATAREP_STRING is defined in mpi.h
MTT caught builds failing with the following error which flagged the problem:
{{{
param.cc:802: error: ‘MPI_MAX_DATAREP_STRING’ was not declared in this scope
}}}

This commit was SVN r21337.

The following SVN revision numbers were found above:
  r21308 --> open-mpi/ompi@2f9765926ea6eeba4bf19affff1924915a863629