Resolve duplicate symbols problem
On the Mac at least, the current HEAD of master branch
fails to build due to duplicate symbols:

```text
duplicate symbol '_ompi_isendrecv_context_t_class' in:
    mpi/c/.libs/libmpi_c.a(libmpi_c_profile_la-isendrecv.o)
    mpi/c/.libs/libmpi_c.a(libmpi_c_noprofile_la-isendrecv.o)
duplicate symbol '_ompi_isendrecv_replace_context_t_class' in:
    mpi/c/.libs/libmpi_c.a(libmpi_c_profile_la-isendrecv_replace.o)
    mpi/c/.libs/libmpi_c.a(libmpi_c_noprofile_la-isendrecv_replace.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libmpi.la] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

The problem is caused by non-static declaration of OBJ_CLASS_INSTANCE
of a statically-defined object in the mpi/c area. These files get built
twice - once for the non-profile code, and again for the profile code.
Thus, one must preface the class instance with "static" to avoid
duplicate symbols.

Signed-off-by: Ralph Castain <rhc@pmix.org>