osc/rdma: fix for intel oneapi compiler
without this patch, file no longer compiles using latest
Intel OneAPI compilers:

osc_rdma_accumulate.c:142:41: error: incompatible integer to poin
              ter conversion passing 'uint64_t' (aka 'unsigned long') to parame
              ter of type 'void *' [-Wint-conversion]
14807        target_is_accel = osc_rdma_is_accel(target_address);
14808                                            ^~~~~~~~~~~~~~

Signed-off-by: Howard Pritchard <howardp@lanl.gov>
(cherry picked from commit d840b497b5469fdad287aaa4f7b95f728b5c239b)