Fixes trac:2932: Move VT v5.12.1.2 changes into v1.5 branch
---svn-pre-commit-ignore-below---
r25595
Changes to VT:
	- Use own implementation of assert() to work around a compiler bug (seen on MacOS using GCC v4.2.1):
	  The linker results in an undefined reference to ___builtin_expect() when using assert() within OpenMP-parallel regions.

r25598
Changes to VT:
	- removed unnecessary trailing ';' from several macro definitions

This commit was SVN r25617.

The following SVN revision numbers were found above:
  r25595 --> open-mpi/ompi@b3f4fca3f411c099917a816d3f16f0edb4cbf879
  r25598 --> open-mpi/ompi@701d4edc2b95df3b1d2f1ff3c04384608352181d

The following Trac tickets were found above:
  Ticket 2932 --> https://svn.open-mpi.org/trac/ompi/ticket/2932