This patch fixes
  error: void value not ignored as it ought to be 

in the C/R code by ignoring the return value of functions which 
no longer return a value (only void). 

Signed-off-by: Adrian Reber <adrian.reber@hs-esslingen.de>